# Added for GSTN filing
Gstcredentials:
  client-secret: 29b560eab35a4e42a97a37c03ddbb57a
  client-id: l7xx347ad87258aa48ebb61fcbdab7d19b0b
  content-type: application/json
  app-key: 9b0d686d-f4e3-4b49-a347-22440b8f
  encrypted-app-key: DJNLyKK/XAi6ILg0L0G9t68k4+H5UyvUhEN6nr9gmnwgQf/DSAMSWL+gLcPHkD/hQHh51WwGGioCA7SC8p+Hj6S8tXFazr3a9iHiOsRTOgLBdfNI49pLL9ovhG/40iazPU2JWThRlr5DA53in/x3aGLdyhZoXwfg+ijY3C/jW28pCwXZ5TChgzzPp8WbZenRwfxCaus5JVWs+GNZW+fd7YrgeQ9DDZt/Zis71223chxmhKeawaLYgRdgxjV7E88WUExXskciwCCU9L1GwSLfGbD5nXfq4y6ZvP0WeNWp/ipS6BfgqySer5N8OlxClkdCg4n/Otkv8j/4WBvh8hDWZg==