#  free_plan = Plan.find_by_name('Free')
#  essential_plan = Plan.find_by_name('Essential')
#  basic_plan = Plan.find_by_name('Basic')
#  premium_plan = Plan.find_by_name('Premium')
#  enterprise_plan = Plan.find_by_name('Enterprise')
#   = Plan.find_by_name('Global')
  global_plan = Plan.create(:name => 'Global', :price => 15, :description => 'The global enterprise plan with multi-user accounting with inventory, payroll and crm', :display_name => 'Global Plan')

#  PlanProperty.create(:plan_id => free_plan.id, :name => 'inventoriable', :value => '0', :datatype => 'boolean') 
#  PlanProperty.create(:plan_id => essential_plan.id, :name => 'inventoriable', :value => '0', :datatype => 'boolean') 
#  PlanProperty.create(:plan_id => basic_plan.id, :name => 'inventoriable', :value => '1', :datatype => 'boolean') 
#  PlanProperty.create(:plan_id => premium_plan.id, :name => 'inventoriable', :value => '1', :datatype => 'boolean') 
#  PlanProperty.create(:plan_id => enterprise_plan.id, :name => 'inventoriable', :value => '1', :datatype => 'boolean') 
  PlanProperty.create(:plan_id => global_plan.id, :name => 'inventoriable', :value => '1', :datatype => 'boolean') 
  
#  PlanProperty.create(:plan_id => free_plan.id, :name => 'payroll', :value => '0', :datatype => 'boolean') 
#  PlanProperty.create(:plan_id => essential_plan.id, :name => 'payroll', :value => '0', :datatype => 'boolean') 
#  PlanProperty.create(:plan_id => basic_plan.id, :name => 'payroll', :value => '0', :datatype => 'boolean') 
#  PlanProperty.create(:plan_id => premium_plan.id, :name => 'payroll', :value => '1', :datatype => 'boolean') 
#  PlanProperty.create(:plan_id => enterprise_plan.id, :name => 'payroll', :value => '1', :datatype => 'boolean') 

#  PlanProperty.create(:plan_id => free_plan.id, :name => 'free_plan', :value => '1', :datatype => 'boolean') 
#  PlanProperty.create(:plan_id => essential_plan.id, :name => 'free_plan', :value => '0', :datatype => 'boolean') 
#  PlanProperty.create(:plan_id => basic_plan.id, :name => 'free_plan', :value => '0', :datatype => 'boolean') 
#  PlanProperty.create(:plan_id => premium_plan.id, :name => 'free_plan', :value => '0', :datatype => 'boolean') 
#  PlanProperty.create(:plan_id => enterprise_plan.id, :name => 'free_plan', :value => '0', :datatype => 'boolean') 
  # PlanProperty.create(:plan_id => global_plan.id, :name => 'free_plan', :value => '1', :datatype => 'boolean') 
 PlanProperty.create(:plan_id => global_plan.id, :name => 'foreign_plan', :value => '1', :datatype => 'boolean') 
